export default [
	{ value: 'none', label: 'None' },
	{ value: 'us', label: 'United States' },
	{ value: 'ca', label: 'Canada' },
	{ value: 'de', label: 'Germany' },
	{ value: 'gb', label: 'United Kingdom' },
	{ value: 'au', label: 'Australia' },
	{ value: 'af', label: 'Afghanistan' },
	{ value: 'ax', label: 'Aland Islands' },
	{ value: 'al', label: 'Albania' },
	{ value: 'dz', label: 'Algeria' },
	{ value: 'as', label: 'American Samoa' },
	{ value: 'ad', label: 'Andorra' },
	{ value: 'ao', label: 'Angola' },
	{ value: 'ai', label: 'Anguilla' },
	{ value: 'ag', label: 'Antigua' },
	{ value: 'ar', label: 'Argentina' },
	{ value: 'am', label: 'Armenia' },
	{ value: 'aw', label: 'Aruba' },
	{ value: 'at', label: 'Austria' },
	{ value: 'az', label: 'Azerbaijan' },
	{ value: 'bs', label: 'Bahamas' },
	{ value: 'bh', label: 'Bahrain' },
	{ value: 'bd', label: 'Bangladesh' },
	{ value: 'bb', label: 'Barbados' },
	{ value: 'by', label: 'Belarus' },
	{ value: 'be', label: 'Belgium' },
	{ value: 'bz', label: 'Belize' },
	{ value: 'bj', label: 'Benin' },
	{ value: 'bm', label: 'Bermuda' },
	{ value: 'bt', label: 'Bhutan' },
	{ value: 'bo', label: 'Bolivia' },
	{ value: 'ba', label: 'Bosnia' },
	{ value: 'bw', label: 'Botswana' },
	{ value: 'bv', label: 'Bouvet Island' },
	{ value: 'br', label: 'Brazil' },
	{ value: 'vg', label: 'British Virgin Islands' },
	{ value: 'bn', label: 'Brunei' },
	{ value: 'bg', label: 'Bulgaria' },
	{ value: 'bf', label: 'Burkina Faso' },
	{ value: 'mm', label: 'Burma' },
	{ value: 'bi', label: 'Burundi' },
	{ value: 'tc', label: 'Caicos Islands' },
	{ value: 'kh', label: 'Cambodia' },
	{ value: 'cm', label: 'Cameroon' },
	{ value: 'cn', label: 'China' },
	{ value: 'cv', label: 'Cape Verde' },
	{ value: 'ky', label: 'Cayman Islands' },
	{ value: 'cf', label: 'Central African Republic' },
	{ value: 'td', label: 'Chad' },
	{ value: 'cl', label: 'Chile' },
	{ value: 'cx', label: 'Christmas Island' },
	{ value: 'cc', label: 'Cocos Islands' },
	{ value: 'co', label: 'Colombia' },
	{ value: 'km', label: 'Comoros' },
	{ value: 'cg', label: 'Congo Brazzaville' },
	{ value: 'cd', label: 'Congo' },
	{ value: 'ck', label: 'Cook Islands' },
	{ value: 'cr', label: 'Costa Rica' },
	{ value: 'ci', label: 'Cote Divoire' },
	{ value: 'hr', label: 'Croatia' },
	{ value: 'cu', label: 'Cuba' },
	{ value: 'cy', label: 'Cyprus' },
	{ value: 'cz', label: 'Czech Republic' },
	{ value: 'dk', label: 'Denmark' },
	{ value: 'dj', label: 'Djibouti' },
	{ value: 'dm', label: 'Dominica' },
	{ value: 'do', label: 'Dominican Republic' },
	{ value: 'ec', label: 'Ecuador' },
	{ value: 'eg', label: 'Egypt' },
	{ value: 'sv', label: 'El Salvador' },
	{ value: 'gq', label: 'Equatorial Guinea' },
	{ value: 'er', label: 'Eritrea' },
	{ value: 'ee', label: 'Estonia' },
	{ value: 'et', label: 'Ethiopia' },
	{ value: 'eu', label: 'European Union' },
	{ value: 'fk', label: 'Falkland Islands' },
	{ value: 'fo', label: 'Faroe Islands' },
	{ value: 'fj', label: 'Fiji' },
	{ value: 'fi', label: 'Finland' },
	{ value: 'fr', label: 'France' },
	{ value: 'gf', label: 'French Guiana' },
	{ value: 'pf', label: 'French Polynesia' },
	{ value: 'tf', label: 'French Territories' },
	{ value: 'ga', label: 'Gabon' },
	{ value: 'gm', label: 'Gambia' },
	{ value: 'ge', label: 'Georgia' },
	{ value: 'gh', label: 'Ghana' },
	{ value: 'gi', label: 'Gibraltar' },
	{ value: 'gr', label: 'Greece' },
	{ value: 'gl', label: 'Greenland' },
	{ value: 'gd', label: 'Grenada' },
	{ value: 'gp', label: 'Guadeloupe' },
	{ value: 'gu', label: 'Guam' },
	{ value: 'gt', label: 'Guatemala' },
	{ value: 'gw', label: 'Guinea-Bissau' },
	{ value: 'gn', label: 'Guinea' },
	{ value: 'gy', label: 'Guyana' },
	{ value: 'ht', label: 'Haiti' },
	{ value: 'hm', label: 'Heard Island' },
	{ value: 'hn', label: 'Honduras' },
	{ value: 'hk', label: 'Hong Kong' },
	{ value: 'hu', label: 'Hungary' },
	{ value: 'is', label: 'Iceland' },
	{ value: 'in', label: 'India' },
	{ value: 'io', label: 'Indian Ocean Territory' },
	{ value: 'id', label: 'Indonesia' },
	{ value: 'ir', label: 'Iran' },
	{ value: 'iq', label: 'Iraq' },
	{ value: 'ie', label: 'Ireland' },
	{ value: 'il', label: 'Israel' },
	{ value: 'it', label: 'Italy' },
	{ value: 'jm', label: 'Jamaica' },
	{ value: 'jp', label: 'Japan' },
	{ value: 'jo', label: 'Jordan' },
	{ value: 'kz', label: 'Kazakhstan' },
	{ value: 'ke', label: 'Kenya' },
	{ value: 'ki', label: 'Kiribati' },
	{ value: 'kw', label: 'Kuwait' },
	{ value: 'kg', label: 'Kyrgyzstan' },
	{ value: 'la', label: 'Laos' },
	{ value: 'lv', label: 'Latvia' },
	{ value: 'lb', label: 'Lebanon' },
	{ value: 'ls', label: 'Lesotho' },
	{ value: 'lr', label: 'Liberia' },
	{ value: 'ly', label: 'Libya' },
	{ value: 'li', label: 'Liechtenstein' },
	{ value: 'lt', label: 'Lithuania' },
	{ value: 'lu', label: 'Luxembourg' },
	{ value: 'mo', label: 'Macau' },
	{ value: 'mk', label: 'Macedonia' },
	{ value: 'mg', label: 'Madagascar' },
	{ value: 'mw', label: 'Malawi' },
	{ value: 'my', label: 'Malaysia' },
	{ value: 'mv', label: 'Maldives' },
	{ value: 'ml', label: 'Mali' },
	{ value: 'mt', label: 'Malta' },
	{ value: 'mh', label: 'Marshall Islands' },
	{ value: 'mq', label: 'Martinique' },
	{ value: 'mr', label: 'Mauritania' },
	{ value: 'mu', label: 'Mauritius' },
	{ value: 'yt', label: 'Mayotte' },
	{ value: 'mx', label: 'Mexico' },
	{ value: 'fm', label: 'Micronesia' },
	{ value: 'md', label: 'Moldova' },
	{ value: 'mc', label: 'Monaco' },
	{ value: 'mn', label: 'Mongolia' },
	{ value: 'me', label: 'Montenegro' },
	{ value: 'ms', label: 'Montserrat' },
	{ value: 'ma', label: 'Morocco' },
	{ value: 'mz', label: 'Mozambique' },
	{ value: 'na', label: 'Namibia' },
	{ value: 'nr', label: 'Nauru' },
	{ value: 'np', label: 'Nepal' },
	{ value: 'an', label: 'Netherlands Antilles' },
	{ value: 'nl', label: 'Netherlands' },
	{ value: 'nc', label: 'New Caledonia' },
	{ value: 'pg', label: 'New Guinea' },
	{ value: 'nz', label: 'New Zealand' },
	{ value: 'ni', label: 'Nicaragua' },
	{ value: 'ne', label: 'Niger' },
	{ value: 'ng', label: 'Nigeria' },
	{ value: 'nu', label: 'Niue' },
	{ value: 'nf', label: 'Norfolk Island' },
	{ value: 'kp', label: 'North Korea' },
	{ value: 'mp', label: 'Northern Mariana Islands' },
	{ value: 'no', label: 'Norway' },
	{ value: 'om', label: 'Oman' },
	{ value: 'pk', label: 'Pakistan' },
	{ value: 'pw', label: 'Palau' },
	{ value: 'ps', label: 'Palestine' },
	{ value: 'pa', label: 'Panama' },
	{ value: 'py', label: 'Paraguay' },
	{ value: 'pe', label: 'Peru' },
	{ value: 'ph', label: 'Philippines' },
	{ value: 'pn', label: 'Pitcairn Islands' },
	{ value: 'pl', label: 'Poland' },
	{ value: 'pt', label: 'Portugal' },
	{ value: 'pr', label: 'Puerto Rico' },
	{ value: 'qa', label: 'Qatar' },
	{ value: 're', label: 'Reunion' },
	{ value: 'ro', label: 'Romania' },
	{ value: 'ru', label: 'Russia' },
	{ value: 'rw', label: 'Rwanda' },
	{ value: 'sh', label: 'Saint Helena' },
	{ value: 'kn', label: 'Saint Kitts and Nevis' },
	{ value: 'lc', label: 'Saint Lucia' },
	{ value: 'pm', label: 'Saint Pierre' },
	{ value: 'vc', label: 'Saint Vincent' },
	{ value: 'ws', label: 'Samoa' },
	{ value: 'sm', label: 'San Marino' },
	{ value: 'gs', label: 'Sandwich Islands' },
	{ value: 'st', label: 'Sao Tome' },
	{ value: 'sa', label: 'Saudi Arabia' },
	{ value: 'gb sct', label: 'Scotland' },
	{ value: 'sn', label: 'Senegal' },
	{ value: 'rs', label: 'Serbia' },
	{ value: 'sc', label: 'Seychelles' },
	{ value: 'sl', label: 'Sierra Leone' },
	{ value: 'sg', label: 'Singapore' },
	{ value: 'sk', label: 'Slovakia' },
	{ value: 'si', label: 'Slovenia' },
	{ value: 'sb', label: 'Solomon Islands' },
	{ value: 'so', label: 'Somalia' },
	{ value: 'za', label: 'South Africa' },
	{ value: 'kr', label: 'South Korea' },
	{ value: 'es', label: 'Spain' },
	{ value: 'lk', label: 'Sri Lanka' },
	{ value: 'sd', label: 'Sudan' },
	{ value: 'sr', label: 'Suriname' },
	{ value: 'sj', label: 'Svalbard' },
	{ value: 'sz', label: 'Swaziland' },
	{ value: 'se', label: 'Sweden' },
	{ value: 'ch', label: 'Switzerland' },
	{ value: 'sy', label: 'Syria' },
	{ value: 'tw', label: 'Taiwan' },
	{ value: 'tj', label: 'Tajikistan' },
	{ value: 'tz', label: 'Tanzania' },
	{ value: 'th', label: 'Thailand' },
	{ value: 'tl', label: 'Timorleste' },
	{ value: 'tg', label: 'Togo' },
	{ value: 'tk', label: 'Tokelau' },
	{ value: 'to', label: 'Tonga' },
	{ value: 'tt', label: 'Trinidad' },
	{ value: 'tn', label: 'Tunisia' },
	{ value: 'tr', label: 'Turkey' },
	{ value: 'tm', label: 'Turkmenistan' },
	{ value: 'tv', label: 'Tuvalu' },
	{ value: 'ug', label: 'Uganda' },
	{ value: 'ua', label: 'Ukraine' },
	{ value: 'ae', label: 'United Arab Emirates' },
	{ value: 'uy', label: 'Uruguay' },
	{ value: 'um', label: 'Us Minor Islands' },
	{ value: 'vi', label: 'Us Virgin Islands' },
	{ value: 'uz', label: 'Uzbekistan' },
	{ value: 'vu', label: 'Vanuatu' },
	{ value: 'va', label: 'Vatican City' },
	{ value: 've', label: 'Venezuela' },
	{ value: 'vn', label: 'Vietnam' },
	{ value: 'gb wls', label: 'Wales' },
	{ value: 'wf', label: 'Wallis and Futuna' },
	{ value: 'eh', label: 'Western Sahara' },
	{ value: 'ye', label: 'Yemen' },
	{ value: 'zm', label: 'Zambia' },
	{ value: 'zw', label: 'Zimbabwe' },
];
